### ISSUE TITLE
iCal link doesn't appear to work

### ISSUE THREAD

**Issue by SpencerDub** [rosszurowski/small-seasons#3]
When I click [the iCal link](https://is.gd/3QB6JT) at the bottom of the page, nothing happens. Nothing downloads, I'm not taken to another page--nothing.

Additionally, when I attempt to add the iCal version of the calendar to my NextCloud calendar by copy-pasting [the same link](https://is.gd/3QB6JT), I get this error message:

> Error requesting resource on remote server. This could possible be related to a certificate mismatch

Finally, when I paste [the iCal link](https://is.gd/3QB6JT) into my browser URL bar and attempt to visit it, nothing happens. No page loads; I'm left on a blank "New Tab" page.

**Comment by rosszurowski** [comment]
I suspect either Google Calendar or macOS changed their default behaviour along the way and now it's broken. In any case, I've created [a short guide to subscribing via iCal](https://gist.github.com/rosszurowski/c7132bf37f7344a775e262619f97ff18) and linked it from the site in c6d2ec6. I've tested it with an iCloud-hosted calendar, but do let me know if you run into troubles with NextCloud too. Thanks for reporting!
