### ISSUE TITLE
Mastodon bot?

### ISSUE THREAD

**Issue by mrzool** [rosszurowski/small-seasons#5]
Hey @rosszurowski, I love your Twitter bot, but due to recent events I assume it will stop working soon. 

Any plan for a Mastodon bot?

**Comment by rosszurowski** [comment]
It already exists! I realized I updated the other repo, but I'll add a note here and on Twitter as well. Once the API limitations kick-in, I may tweet from Small Seasons Bot too.

https://botsin.space/@smallseasons

**Comment by mrzool** [comment]
That's great to hear, thanks @rosszurowski!
